# _NAME-HARSH YADAV_
# _STUDENT ID-8977229_

In [2]:
import numpy as np

In [10]:
def no_zeros(arrayInput):

    return not np.isin(0, arrayInput).any()

input = np.array([1, 2, 3, 4, 5, 6, 0])
result = no_zeros(input)
print(result)

False


In [23]:

def linearly_distributed(n, min, max):
    result=np.array(np.linspace(min, max, n, dtype=int))
    return result
result = linearly_distributed(4,0,100-1)
print(result)

[ 0 33 66 99]


In [18]:
def two_dimensions(n):
    array = np.zeros((n, n))

   
    array[0, :] = 1  # top row
    array[-1, :] = 1  # bottom row
    array[:, 0] = 1  # left column
    array[:, -1] = 1  # right column

    return array
n = 3
result = two_dimensions(n)
print(result) 

    

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


In [19]:
def create_array(n,min,max):
    array = np.random.randint(min, max, n)   #random numbers
    return array

print(create_array(10,0,10))


[0 1 2 8 8 9 8 6 7 4]


In [20]:
def random_generation(n,min,max):
    
    array = np.random.choice(np.arange(min, max+1), size=n*n, replace=False) 
    array = array.reshape(n, n) # Reshape
    return array

print(random_generation(3,0,12))

[[ 1  8  0]
 [10  3  7]
 [11  2 12]]
